/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.dokter.form;

import application.base.BaseDataTableFrame;
import application.dokter.Dokter;
import application.menu.MenuFrame;
import javax.swing.DefaultComboBoxModel;
import application.util.Callback;

/**
 *
 * @author Azis Naufal
 */
public class DokterFormInternalFrame extends BaseDataTableFrame implements DokterFormView {
    private DokterFormPresenter presenter = null;
    private Callback callback = null;

    /**
     * Creates new form DokterInternalFrame
     */
    public DokterFormInternalFrame(Dokter dokter) {
        presenter = new DokterFormPresenter(this);
        initComponents();
        if (dokter != null){
            presenter.setDokter(dokter);
            setTitle("Ubah Data Dokter");
        }
    }
    
    public void setCallback(Callback callback){
        this.callback = callback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblSpesialis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtNama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        cbxSpesialis = new javax.swing.JComboBox<>();

        btnKembali.setMnemonic('t');
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        lblNama.setText("Nama");

        lblAlamat.setText("Alamat");

        lblSpesialis.setText("Spesialis");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtAlamat);

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        cbxSpesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Umum", "THT", "Psikolog Non Klinis", "Ibu dan Anak" }));
        cbxSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSpesialisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpesialis)
                            .addComponent(lblNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(cbxSpesialis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpesialis)
                    .addComponent(cbxSpesialis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlamat)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (txtNama.getText().isEmpty()){
            showError("Nama tidak boleh kosong!");
        }
        else if (cbxSpesialis.getSelectedIndex() == 0){
            showError("Spesialis tidak boleh kosong!");
        }
        else if (txtAlamat.getText().isEmpty()){
            showError("Alamat tidak boleh kosong!");
        }
        else {
            setWaitCursor();
            presenter.save();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        // TODO add your handling code here:
        presenter.setNama(txtNama.getText());
    }//GEN-LAST:event_txtNamaKeyReleased

    private void txtAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyReleased
        // TODO add your handling code here:
        presenter.setAlamat(txtAlamat.getText());
    }//GEN-LAST:event_txtAlamatKeyReleased

    private void cbxSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSpesialisActionPerformed
        // TODO add your handling code here:
        presenter.setSpesialis(cbxSpesialis.getSelectedItem().toString());
    }//GEN-LAST:event_cbxSpesialisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxSpesialis;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSpesialis;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    @Override
    protected String setWindowTitle() {
        return "Tambah Data Dokter";
    }

    @Override
    public void showData(Dokter dokter) {
        txtNama.setText(dokter.getNama());
        txtAlamat.setText(dokter.getAlamat());
        DefaultComboBoxModel cbxSpesialisModel = (DefaultComboBoxModel) cbxSpesialis.getModel();
        for (int i = 0; i < cbxSpesialisModel.getSize(); i++){
            if (cbxSpesialisModel.getElementAt(i).equals(dokter.getSpesialis())){
                cbxSpesialisModel.setSelectedItem(i);
            }
        }
    }

    @Override
    public void showSuccess(String s) {
        this.showMessageSuccess(s);
        setDefaultCursor();
    }

    @Override
    public void showError(String s) {
        this.showMessageError(s);
        setDefaultCursor();
    }

    @Override
    public void back() {
        MenuFrame menuFramee = MenuFrame.getInstance();
        menuFramee.removeOneDesktopPane(DokterFormInternalFrame.this);
        if (callback != null)
            callback.onFinish();
        dispose();
    }
}
