/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.pemeriksaan.form.tindak;

import application.base.BaseDataTableFrame;
import javax.swing.DefaultComboBoxModel;
import application.util.CallbackReturn;

/**
 *
 * @author Azis Naufal
 */
public class TindakFormInternalFrame extends BaseDataTableFrame implements TindakFormView{
    private static TindakFormInternalFrame instance = null;
    private TindakFormPresenter presenter = null;
    private CallbackReturn callback = null;
    /**
     * Creates new form TercatatFormInternalFrame
     */
    private TindakFormInternalFrame(Tindak tindak) {
        this.presenter = new TindakFormPresenter(this);
        initComponents();
        loadData();
        if (tindak != null)
            presenter.setTindak(tindak);
    }
    
    public static TindakFormInternalFrame getInstance(Tindak tindak){
        if (instance == null){
            instance = new TindakFormInternalFrame(tindak);
        }
        return instance;
    }
    
    public void setCallback(CallbackReturn callback){
        this.callback = callback;
    }
    
    private void loadData(){
        setWaitCursor();
        presenter.loadData();
        setDefaultCursor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaTindakan = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        cbxTindakan = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        lblNamaTindakan.setText("Nama Tindakan");

        lblHarga.setText("Harga");

        cbxTindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTindakanActionPerformed(evt);
            }
        });

        txtHarga.setEditable(false);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaTindakan)
                            .addComponent(lblHarga))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga)
                            .addComponent(cbxTindakan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaTindakan)
                    .addComponent(cbxTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTindakanActionPerformed
        // TODO add your handling code here:
        presenter.setId_tindakan(cbxTindakan.getSelectedIndex());
    }//GEN-LAST:event_cbxTindakanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        presenter.validate();
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxTindakan;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblNamaTindakan;
    private javax.swing.JTextField txtHarga;
    // End of variables declaration//GEN-END:variables

    @Override
    public void loadTindakan(String[] tindakans) {
        cbxTindakan.setModel(new DefaultComboBoxModel<>(tindakans));
    }

    @Override
    protected String setWindowTitle() {
        return "Tindakan";
    }

    @Override
    public void showHarga(String harga) {
        txtHarga.setText(harga);
    }

    @Override
    public void showData(Tindak tindak) {
        cbxTindakan.setSelectedItem(tindak.getNama_tindakan());
        txtHarga.setText("Rp " + tindak.getHarga());
    }

    @Override
    public void back() {
        callback.onFinish(presenter.getTindak());
        instance = null;
        dispose();
    }

    @Override
    public void showSuccess(String s) {
        this.showMessageSuccess(s);
        setDefaultCursor();
    }

    @Override
    public void showError(String s) {
        this.showMessageError(s);
        setDefaultCursor();
    }
}
