/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package application.pasien.form;

import application.base.baseDataTableFrame;
import application.menu.menuFrame;
import application.pasien.pasien;
import javax.swing.DefaultComboBoxModel;
import application.util.callback;

/**
 *
 * @author Lenovo
 */
public class pasienFormInternalFrame extends baseDataTableFrame implements pasienFormView {
    private pasienFormPresenter presenter = null;
    private callback callback = null;
    
    /**
     * Creates new form PasienFormInternalFrame
     */
    public pasienFormInternalFrame(pasien pasien) {
        presenter = new pasienFormPresenter(this);
        
        initComponents();
        
        if (pasien != null) {
            presenter.setPasien(pasien);
            setTitle("Ubah Data Pasien");
        }
    }
    
    @Override
    public void showData(pasien pasien) {
        
        txtNama.setText(pasien.getNama());
        txtAlamat.setText(pasien.getAlamat());
        formattedTxtUmur.setText(pasien.getUmur());
        
        DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel) cbxJenisKelamin.getModel();
        
        for (int i = 0; i < defaultComboBoxModel.getSize(); i++) {
            if (defaultComboBoxModel.getElementAt(i).equals(pasien.getJenis_kelamin())); {
                defaultComboBoxModel.setSelectedItem(i);
            }
        }
    }
    
    public void setCallback(callback callback){
        this.callback = callback;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblJenisKelamin = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        cbxJenisKelamin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        lblUmur = new javax.swing.JLabel();
        formattedTxtUmur = new javax.swing.JFormattedTextField();

        btnKembali.setMnemonic('t');
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        lblNama.setText("Nama");

        lblAlamat.setText("Alamat");

        lblJenisKelamin.setText("Jenis Kelamin");

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        cbxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pria", "Wanita" }));
        cbxJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJenisKelaminActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        lblUmur.setText("Umur");

        formattedTxtUmur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        formattedTxtUmur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formattedTxtUmurKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJenisKelamin)
                            .addComponent(lblNama)
                            .addComponent(lblUmur)
                            .addComponent(lblAlamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formattedTxtUmur))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJenisKelamin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUmur)
                    .addComponent(formattedTxtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_btnKembaliActionPerformed
    
    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        // TODO add your handling code here:
        presenter.setNama(txtNama.getText());
    }//GEN-LAST:event_txtNamaKeyReleased
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (txtNama.getText().isEmpty()){
            showError("Nama tidak boleh kosong!");
        }
        else if (cbxJenisKelamin.getSelectedItem().equals("-")) {
            showError("Jenis Kelamin tidak boleh kosong");
        }
        else if (txtAlamat.getText().isEmpty()){
            showError("Alamat tidak boleh kosong!");
        } else if (formattedTxtUmur.getText().isEmpty()) {
            showError("Umur tidak boleh kosong");
        }
        else {
            setWaitCursor();
            presenter.save();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    
    private void txtAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyReleased
        presenter.setAlamat(txtAlamat.getText());
    }//GEN-LAST:event_txtAlamatKeyReleased
    
    private void cbxJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJenisKelaminActionPerformed
        if (cbxJenisKelamin.getSelectedItem().toString() == "Pria") {
            presenter.setJenisKelamin("P");
        } else {
            presenter.setJenisKelamin("W");
        }
    }//GEN-LAST:event_cbxJenisKelaminActionPerformed
    
    private void formattedTxtUmurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formattedTxtUmurKeyReleased
        presenter.setUmur(formattedTxtUmur.getText());
    }//GEN-LAST:event_formattedTxtUmurKeyReleased
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxJenisKelamin;
    private javax.swing.JFormattedTextField formattedTxtUmur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblUmur;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
    
    @Override
    protected String setWindowTitle() {
        return "Tambah Data Pasien";
    }
    
    @Override
    public void back() {
        setWaitCursor();
        
        menuFrame menuFramee = menuFrame.getInstance();
        menuFramee.removeOneDesktopPane(pasienFormInternalFrame.this);
        if (callback != null){
            callback.onFinish();
        }
        setDefaultCursor();
        dispose();
    }
    
    @Override
    public void showSuccess(String s) {
        this.showMessageSuccess(s);
        setDefaultCursor();
    }
    
    @Override
    public void showError(String s) {
        this.showMessageError(s);
        setDefaultCursor();
    }
}
